// Preguntas para la fase "La Pregunta". Se responden desde el cuerpo en el que estás:
// ¿contestas como tú… o como contestaría la persona dueña de ese cuerpo?
export const QUESTIONS = [
  "¿Cuál es la comida que más odias?",
  "¿Qué harías con un millón de dólares mañana?",
  "¿Cuál es tu mayor miedo irracional?",
  "¿Qué canción te sabes completa aunque te dé pena?",
  "Describe tu día perfecto en una frase.",
  "¿Qué es lo más raro que has comido?",
  "Si fueras un animal, ¿cuál serías y por qué?",
  "¿Cuál fue tu peor corte de pelo?",
  "¿Qué app borrarías del mundo?",
  "¿Cuál es tu placer culposo?",
  "¿Qué superpoder inútil te gustaría tener?",
  "¿A qué hora te despiertas un domingo?",
  "¿Qué dirías en tu discurso de los Óscar?",
  "¿Qué es lo primero que haces al llegar a casa?",
  "¿Cuál es tu excusa favorita para no salir?",
  "¿Qué emoji usas demasiado?",
  "¿Cuál es la peor película que te gustó?",
  "¿Qué hiciste de niño que tus papás nunca supieron?",
  "Si tu vida fuera una serie, ¿cómo se llamaría?",
  "¿Qué comida pedirías como última cena?",
  "¿Cuál es tu opinión más polémica?",
  "¿Qué te hace reír aunque no deberías?",
  "¿A qué famoso le escribirías por DM?",
  "¿Qué objeto rescatarías si se quema tu casa?",
  "¿Qué es lo más vergonzoso que buscaste en Google?",
  "¿Cuál es tu frase o muletilla más usada?",
  "¿Piña en la pizza: sí o no? Defiéndete.",
  "¿Qué trabajo nunca podrías hacer?",
  "¿Cuál es tu talento oculto?",
  "¿Qué le dirías a tu yo de 12 años?",
];
